### ISSUE TITLE
Height parameter ignored.

### ISSUE THREAD

**Issue by xbony2** [HydraWiki/CurseTwitter#1]
As tested [here](https://transformersthedarkeras.gamepedia.com/User:Xbony2/sandbox), adjusting the height parameter appears to do nothing. I know the height must be above 200, my tests were above that. Starting at say, 201, and changing it to 800, I see no visual change (I tried other random numbers and whatnot) so I assume this parameter is broken for whatever reason.

(If you can ping "noveria" on Slack if/when this is fixed that would be cool)

**Comment by Alexia** [comment]
Fixed in 4708fd49d4f11001bb92a35f076b3ff8155b2e0c.
